#!/bin/bash

if [[ "x$1" == "x" ]];then
    echo "$0 <key_word>"
    exit
fi

ps axu | grep "$1" | grep -v "grep" | grep -v "showpid"
ps axu | grep "$1" | grep -v "grep" | grep -v "$0" | awk '{print $2}' | sort -gr | head -n 1
